extends: standard
rules:
  semi: 
    - error
    - always
  quotes: 
    - error
    - double
  indent: 
    - error
    - 4
    - MemberExpression: 2
  space-before-function-paren:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline