extends: standard
rules:
    semi:
      - error
      - always
    quotes:
      - error
      - double
      - allowTemplateLiterals: true
    indent:
      - error
      - 4
      - MemberExpression: 2
        SwitchCase: 1
        ignoredNodes:
          - ForOfStatement
          - ForInStatement
    space-before-function-paren:
      - error
      - never
    comma-dangle:
      - error
      - always-multiline
    key-spacing:
      - error
      - singleLine:
            beforeColon: false
            afterColon: true
            mode: minimum
        multiLine:
            beforeColon: false
            align:
                beforeColon: false
                afterColon: true
                on: value
            mode: minimum
    object-curly-spacing:
      - error
      - never
    eol-last:
      - error
      - always
    no-multiple-empty-lines:
      - error
      - max: 2
        maxEOF: 1
    yoda:
      - error
      - never
      - exceptRange: true
    spaced-comment:
      - error
      - always
      - line:
            exceptions:
              - "/"
    max-len:
      - error
      - code: 79
    no-multi-spaces:
      - off
      - exceptions:
          # Using https://eslint.org/parser/
          VariableDeclarator: true
          AssignmentExpression: true
          BlockStatement: true
    import/named:
      - error
      - always
    import/no-unresolved:
      - error
      - always
    import/no-cycle:
      - error
      - always
    no-shadow:
      - error
      - hoist: all
    no-extra-semi:
      - error

