extends: standard
rules:
  semi: 
    - error
    - always
  quotes: 
    - error
    - double
  indent: 
    - error
    - 4
    - MemberExpression: 2
  space-before-function-paren:
    - error
    - never
  comma-dangle:
    - error
    - only-multiline
  key-spacing:
    - error
    - singleLine:
          beforeColon: false
          afterColon: true
      multiLine:
          beforeColon: false
          align: 
              beforeColon: false
              afterColon: true
              on: value
  object-curly-spacing:
    - error
    - never
